In [75]:
text_data = ""

with open(r"C:\Workspace-ML\text_data\BM\ISS.txt", encoding="utf-8") as file:
    text_data = file.read()

vocab = sorted(list(set(text_data)))
vocab = "".join(vocab)
vocab_size = len(vocab)
print(len(vocab))
vocab

69


'\n ",.0123456789:?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'

In [17]:
ch2id = {}
id2ch = {}
for idx, ele in enumerate(vocab):
    ch2id[ele] = idx
    id2ch[idx] = ele

In [18]:
ch2id

{'\n': 0,
 ' ': 1,
 '"': 2,
 ',': 3,
 '.': 4,
 '0': 5,
 '1': 6,
 '2': 7,
 '3': 8,
 '4': 9,
 '5': 10,
 '6': 11,
 '7': 12,
 '8': 13,
 '9': 14,
 ':': 15,
 '?': 16,
 'A': 17,
 'B': 18,
 'C': 19,
 'D': 20,
 'E': 21,
 'F': 22,
 'G': 23,
 'H': 24,
 'I': 25,
 'J': 26,
 'K': 27,
 'L': 28,
 'M': 29,
 'N': 30,
 'O': 31,
 'P': 32,
 'Q': 33,
 'R': 34,
 'S': 35,
 'T': 36,
 'U': 37,
 'V': 38,
 'W': 39,
 'X': 40,
 'Y': 41,
 'Z': 42,
 'a': 43,
 'b': 44,
 'c': 45,
 'd': 46,
 'e': 47,
 'f': 48,
 'g': 49,
 'h': 50,
 'i': 51,
 'j': 52,
 'k': 53,
 'l': 54,
 'm': 55,
 'n': 56,
 'o': 57,
 'p': 58,
 'q': 59,
 'r': 60,
 's': 61,
 't': 62,
 'u': 63,
 'v': 64,
 'w': 65,
 'x': 66,
 'y': 67,
 'z': 68}

In [19]:
id2ch

{0: '\n',
 1: ' ',
 2: '"',
 3: ',',
 4: '.',
 5: '0',
 6: '1',
 7: '2',
 8: '3',
 9: '4',
 10: '5',
 11: '6',
 12: '7',
 13: '8',
 14: '9',
 15: ':',
 16: '?',
 17: 'A',
 18: 'B',
 19: 'C',
 20: 'D',
 21: 'E',
 22: 'F',
 23: 'G',
 24: 'H',
 25: 'I',
 26: 'J',
 27: 'K',
 28: 'L',
 29: 'M',
 30: 'N',
 31: 'O',
 32: 'P',
 33: 'Q',
 34: 'R',
 35: 'S',
 36: 'T',
 37: 'U',
 38: 'V',
 39: 'W',
 40: 'X',
 41: 'Y',
 42: 'Z',
 43: 'a',
 44: 'b',
 45: 'c',
 46: 'd',
 47: 'e',
 48: 'f',
 49: 'g',
 50: 'h',
 51: 'i',
 52: 'j',
 53: 'k',
 54: 'l',
 55: 'm',
 56: 'n',
 57: 'o',
 58: 'p',
 59: 'q',
 60: 'r',
 61: 's',
 62: 't',
 63: 'u',
 64: 'v',
 65: 'w',
 66: 'x',
 67: 'y',
 68: 'z'}

In [21]:
def encode(text):
    return [ch2id[char] for char in text]

encode("hii")

[50, 51, 51]

In [25]:
def decode(tokens):
    return "".join([id2ch[token] for token in tokens])

print(decode(encode("hii, who?")))
decode([50, 51, 51])

hii, who?


'hii'

In [59]:
text_data_tokens = torch.tensor(encode(text_data), dtype = torch.long)
len(text_data_tokens)

529000

In [60]:
n = int(0.9*len(text_data_tokens))
print(n)
train_data = text_data_tokens[:n]
val_data = text_data_tokens[n:]

len(train_data), len(val_data)

476100


(476100, 52900)

In [61]:
block_size = 8
train_data[:block_size+1]

tensor([24, 47, 54, 54, 57,  1, 46, 57, 61])

In [62]:
x = train_data[:block_size]
y = train_data[1:block_size+1]

print(x)
print(y)

tensor([24, 47, 54, 54, 57,  1, 46, 57])
tensor([47, 54, 54, 57,  1, 46, 57, 61])


In [63]:
for i in range(block_size):
    print(f"context: {x[:i+1]} | target: {y[i]}")

context: tensor([24]) | target: 47
context: tensor([24, 47]) | target: 54
context: tensor([24, 47, 54]) | target: 54
context: tensor([24, 47, 54, 54]) | target: 57
context: tensor([24, 47, 54, 54, 57]) | target: 1
context: tensor([24, 47, 54, 54, 57,  1]) | target: 46
context: tensor([24, 47, 54, 54, 57,  1, 46]) | target: 57
context: tensor([24, 47, 54, 54, 57,  1, 46, 57]) | target: 61


In [64]:
"""
We do this so that transformer learn to predict for context size == 1 to context size == 8
"""

'\nWe do this so that transformer learn to predict for context size == 1 to context size == 8\n'

In [65]:
"""
At the time of training, we use Batch processing to utilize the full vRAM.
"""

'\nAt the time of training, we use Batch processing to utilize the full vRAM.\n'

In [84]:
import torch

batch_size = 4 # how many independent sequences we can process in parallel
block_size = 8 # max context length of the model

def get_batch(split):
    """
    torch.randint: return a tensor filled with random integers generated uniformly between low and high
        low: optional, default = 0 
        high,
        size
    
    given a batch_size, 
    creates a list of size batch_size: elements are random int between 0 and [len(data) - block_size]

    torch.stack: concatenates a sequence of tensors along a NEW dimension.
    
    """
    
    
    # split: train / val / test
    data = train_data if split == "train" else val_data

    ix = torch.randint(len(data) - block_size, (batch_size,))
    # print(ix)
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch("train")

print(xb)
print(xb.shape)
print(yb)
print(yb.shape)

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b, t]

        print(f"Context: {context.tolist()} | Target: {target}")

tensor([[60, 47,  1, 44, 43, 43, 54,  1],
        [43, 45, 50, 56, 47,  1, 65, 43],
        [ 1, 49, 43, 43, 56, 46,  1, 55],
        [ 1, 52, 43, 51, 61, 47,  1, 55]])
torch.Size([4, 8])
tensor([[47,  1, 44, 43, 43, 54,  1, 58],
        [45, 50, 56, 47,  1, 65, 43, 54],
        [49, 43, 43, 56, 46,  1, 55, 47],
        [52, 43, 51, 61, 47,  1, 55, 47]])
torch.Size([4, 8])
Context: [60] | Target: 47
Context: [60, 47] | Target: 1
Context: [60, 47, 1] | Target: 44
Context: [60, 47, 1, 44] | Target: 43
Context: [60, 47, 1, 44, 43] | Target: 43
Context: [60, 47, 1, 44, 43, 43] | Target: 54
Context: [60, 47, 1, 44, 43, 43, 54] | Target: 1
Context: [60, 47, 1, 44, 43, 43, 54, 1] | Target: 58
Context: [43] | Target: 45
Context: [43, 45] | Target: 50
Context: [43, 45, 50] | Target: 56
Context: [43, 45, 50, 56] | Target: 47
Context: [43, 45, 50, 56, 47] | Target: 1
Context: [43, 45, 50, 56, 47, 1] | Target: 65
Context: [43, 45, 50, 56, 47, 1, 65] | Target: 43
Context: [43, 45, 50, 56, 47, 1, 65

In [81]:
import torch.nn as nn
from torch.nn import functional as F

class BigramLM(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embeding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        logits = self.token_embeding_table(idx)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, loss = self(idx)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)
        return idx

model = BigramLM(vocab_size)
logits, loss = model(xb, yb)
print(logits.shape)
print(loss)

print(decode(model.generate(idx=torch.zeros((1,1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

torch.Size([32, 69])
tensor(4.8026, grad_fn=<NllLossBackward0>)

h 4c7IRx9z67nMiJs9jtKsa4I0,b7ug3Ypcqx9xuK?MWprpAsa7kDqnrrpi7dOCBD3vqauSeggFlorCUJg"?oigQpSiPJq,xi 2p


In [82]:
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)

In [89]:
batch_size = 32
block_size = 8192
for step in range(1000):
    xb, yb = get_batch("train")
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

    if step % 100 == 0:
        print(loss.item())

print(decode(model.generate(idx=torch.zeros((1,1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

2.4469292163848877
2.432818651199341
2.4584062099456787
2.449742078781128
2.4429216384887695
2.440897226333618
2.450469732284546
2.4535531997680664
2.440206527709961
2.4357717037200928
2.460428237915039
2.4392619132995605
2.4361350536346436
2.440520763397217
2.4500670433044434
2.452646017074585
2.4649605751037598
2.4386425018310547
2.4454948902130127
2.4449870586395264
2.4372308254241943
2.4306118488311768
2.423151969909668
2.4374189376831055
2.42160701751709
2.454564332962036
2.4544692039489746
2.4489715099334717
2.4234354496002197
2.441333770751953
2.4411768913269043
2.4312407970428467
2.446535110473633
2.4426956176757812
2.4419779777526855
2.444112777709961
2.4401042461395264
2.4397411346435547
2.44218111038208
2.4363577365875244
2.4402999877929688
2.4389920234680176
2.435049533843994
2.43784236907959
2.4323503971099854
2.4397053718566895
2.4371793270111084
2.4413344860076904
2.440441131591797
2.447084903717041
2.4290363788604736
2.437694549560547
2.4361937046051025
2.42746949195861

In [90]:
print(decode(model.generate(idx=torch.zeros((1,1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


Charan kagine 1.
Khujalonthaisethe Rgine pn:Q ma. findoture lai thiyar rOW3"
21yiWWoo diLMa.
WBe mon
